package com.GAssociatesWeb.GAssociates.Repository.MasterWebRepository.AssessmentModule_MasterRepository.RVTypes_MasterRepository;

import com.GAssociatesWeb.GAssociates.Entity.MasterWebEntity.AssessmentModule_MasterEntity.RVTypes_MasterEntity.RVTypeCategory_MasterEntity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface RVTypeCategory_MasterRepository extends JpaRepository<RVTypeCategory_MasterEntity, Long> {

}
