package com.GAssociatesWeb.GAssociates.Service.MasterWebServices.AfterAssessmentModule_MasterServices.AfterHearing_Services;

import com.GAssociatesWeb.GAssociates.DTO.MasterWebDto.AfterAssessment_Module.AfterHearing_Dto.AfterHearingCompleteProperty_Dto;

public interface AfterHearingPropertyManagement_MasterService {

    public AfterHearingCompleteProperty_Dto createCompleteProperty(String pdNewPropertyNovc,AfterHearingCompleteProperty_Dto dto, boolean  byRv,boolean byAssessment);
    public AfterHearingCompleteProperty_Dto getCompletePropertyByNewPropertyNo(String newPropertyNo);
}