package com.GAssociatesWeb.GAssociates.DTO.MasterWebDto.AssessmentModule_MasterDto.TaxAssessment_MasterDto;

import com.GAssociatesWeb.GAssociates.DTO.PropertySurveyDto.PropertyDetails_Dto;
import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
public class AssessmentResultsDto {

    private String pdZoneI;
    private String pdWardI;
    private String pdOldpropnoVc;
    private String pdSurypropnoVc;
    private String pdLayoutnameVc;
    private String pdLayoutnoVc;
    private String pdKhasranoVc;
    private String pdPlotnoVc;
    private String pdGrididVc;
    private String pdRoadidVc;
    private String pdParcelidVc;
    private String pdNewpropertynoVc;
    private String pdOwnernameVc;
    private String pdAddnewownernameVc;
    private String pdPannoVc;
    private String pdAadharnoVc;
    private String pdContactnoVc;
    private String pdPropertynameVc;
    private String pdPropertyaddressVc;
    private String pdPincodeVc;
    private String pdCategoryI;
    private String pdPropertytypeI;
    private String pdPropertysubtypeI;
    private String pdUsagetypeI;
    private String pdUsagesubtypeI;
    private String pdBuildingtypeI;
    private String pdBuildingsubtypeI;
    private String pdConstAgeI;
    private String pdConstYearVc;
    private String pdPermissionstatusVc;
    private String pdPermissionnoVc;
    private String pdPermissiondateDt;
    private String pdNooffloorsI;
    private String pdNoofroomsI;
    private String pdStairVc;
    private String pdLiftVc;
    private String pdRoadwidthF;
    private String pdToiletstatusVc;
    private String pdToiletsI;
    private String pdSeweragesVc;
    private String pdSeweragesType;
    private String pdWaterconnstatusVc;
    private String pdWaterconntypeVc;
    private String pdMcconnectionVc;
    private String pdMeternoVc;
    private String pdConsumernoVc;
    private String pdConnectiondateDt;
    private String pdConnectiondateDt_vc;
    private String pdPipesizeF;
    private String pdElectricityconnectionVc;
    private String pdElemeternoVc;
    private String pdEleconsumernoVc;
    private String pdRainwaterhaverstVc;
    private String pdSolarunitVc;
    private String pdPlotareaF;
    private String pdTotbuiltupareaF;
    private String pdTotcarpetareaF;
    private String pdTotalexempareaF;
    private String pdAssesareaF;
    private String pdArealetoutF;
    private String pdAreanotletoutF;
    private String pdCurrassesdateDt;
    private String pdOldrvFl;
    private String user_id;
    private String pdPolytypeVc;
    private String pdStatusbuildingVc;
    private String pdLastassesdateDt;
    private String pdFirstassesdateDt;
    private String pdNoticenoVc;
    private String pdIndexnoVc;
    private String pdNewfinalpropnoVc;
    private String pdTaxstatusVc;
    private String pdChangedVc;
    private String pdNadetailsVc;
    private String pdNanumberI;
    private String pdNadateDt;
    private String pdTddetailsVc;
    private String pdTdordernumF;
    private String pdTddateDt;
    private String pdSaledeedI;
    private String pdSaledateDt;
    private String pdCitysurveynoF;
    private String pdOwnertypeVc;
    private String pdBuildingvalueI;
    private String pdPlotvalueF;
    private String pdTpdateDt;
    private String pdTpdetailsVc;
    private String pdTpordernumF;
    private String pdOccupinameF;
    private String pdPropimageT;
    private String pdHouseplanT;
    private String pdPropimage2T;
    private String pdHouseplan2T;
    private String pdSignT;
    private String pdFinalpropnoVc;
    private String propRefno;
    private String pdImgstatusVc;
    private String pdSuryprop2Vc;
    private String pdSuryprop1Vc;
    private String createdAt;
    private String createddateVc;
    private String updatedAt;
    private String id;
    private String pdApprovedByDesk1Vc;
    private String pdApprovedByDesk2Vc;
    private String pdApprovedByDesk3Vc;
    private String pdCompletedByVc;
    private String pdOldwardNoVc;
    private String pdOldTaxVc;
    private String oldWardNoVc;
    private String oldZoneNoVc;
    private String oldPropertyTypeVc;
    private String oldPropertySubTypeVc;
    private String oldUsageTypeVc;
    private String oldConstructionTypeVc;
    private String oldAssessmentAreaFl;
    private String previousAssessmentDateDt;
    private String currentAssessmentDateDt;
    private String annualRentalValueFl;
    private String annualUnRentalValueFl;
    private String maintainenceRepairAmountConsideredFl;
    private String taxableValueUnRentedFl;
    private String taxableValueRentedFl;
    private String finalValueToConsiderFl;

    private List<PropertyUnitDetailsDto> unitDetails;
    private ConsolidatedTaxDetailsDto consolidatedTaxes;
    private ProposedRatableValueDetailsDto proposedRatableValues;

}
