package com.GAssociatesWeb.GAssociates.DTO.MasterWebDto.AfterAssessment_Module.AfterHearing_Dto;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class AfterHearing_PropertyDetails {

    private Integer id;
    private Integer zone;
    private Integer ward;
    private String oldPropertyNo;
    private String surveyPropertyNo;
    private String layoutName;
    private String layoutNo;
    private String khasraNo;
    private String plotNo;
    private String gridId;
    private String roadId;
    private String parcelId;
    private String newPropertyNo;
    private String ownerName;
    private String additionalOwnerName;
    private String panNo;
    private String aadharNo;
    private String contactNo;
    private String propertyName;
    private String propertyAddress;
    private String pincode;
    private String category;
    private String propertyType;
    private String propertySubType;
    private String usageType;
    private String usageSubType;
    private String buildingType;
    private String buildingSubType;
    private Integer constructionAge;
    private String permissionStatus;
    private String permissionNo;
    private LocalDate permissionDate;
    private Integer numberOfFloors;
    private Integer numberOfRooms;
    private String stair;
    private String lift;
    private String roadWidth;
    private String toiletStatus;
    private Integer toilets;
    private String sewerage;
    private String sewerageType;
    private String waterConnStatus;
    private String waterConnType;
    private String mcConnection;
    private String meterNo;
    private String consumerNo;
    private LocalDate connectionDate;
    private Double pipeSize;
    private String electricityConnection;
    private String eleMeterNo;
    private String eleConsumerNo;
    private String rainwaterHarvesting;
    private String solarUnit;
    private String plotArea;
    private String totalBuiltupArea;
    private String totalCarpetArea;
    private String totalExemptedArea;
    private String assessableArea;
    private String areaLetOut;
    private String areaNotLetOut;
    private LocalDate currentAssessmentDate;
    private String oldRatableValue;
    private String propertyImage;
    private String housePlan;
    private String propertyImage2;
    private String housePlan2;
    private String signature;
    private LocalDate timestamp;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private String userId;
    private String polygonType;
    private String statusOfBuilding;
    private String lastAssessmentDate;
    private String propRefNo;
    private String finalPropertyNo;
    private String imageStatus;
    private Integer surveyProperty2;
    private String surveyProperty1;
    private String noticeNo;
    private String indexNo;
    private String newFinalPropertyNo;
    private Integer taxStatus;
    private Integer changed;
    private String naDetails;
    private String naNumber;
    private String naDate;
    private String tdDetails;
    private String tdOrderNo;
    private String tdDate;
    private String saleDeed;
    private String saleDate;
    private String citySurveyNo;
    private String ownerType;
    private String buildingValue;
    private String plotValue;
    private String tpDate;
    private String tpDetails;
    private String tpOrderNo;
    private String occupierName;
    private Integer surveyProperty3;
}
