package com.GAssociatesWeb.GAssociates.DTO.PropertySurveyDto;

import lombok.Data;

import java.sql.Date;
import java.sql.Timestamp;

@Data
public class UnitBuiltUp_Dto {

    private String pdNewpropertynoVc;//generated in db
    private String udFloorNoVc;//given by unit details
    private Integer udUnitNoVc;//given by unit details
    private Integer ubIdsI;//generated in db
    private String ubDedpercentI;
    private String ubareabefdedFl;
    private String ubplotareaFl;
    private String ubRoomTypeVc;
    private String ubLengthFl;
    private String ubBreadthFl;
    private String ubExemptionsVc;
    private String ubExemLengthFl;
    private String ubExemBreadthFl;
    private String ubExemAreaFl;
    private String ubCarpetAreaFl;
    private String ubAssesAreaFl;
    private Date udTimestampDt;//generated by db
    private String ubLegalStVc;
    private String ubLegalAreaFl;
    private String ubIllegalAreaFl;
    private String udUnitRemarkVc;
    private String ubMeasureTypeVc;
    private Timestamp createdAt;//generated by backend
    private Timestamp updatedAt;//generated by backend
    private Long id;//generated in db/backend

    private UnitDetails_Dto unitDetailsDto;

}
