package com.GAssociatesWeb.GAssociates.Repository.MasterWebRepository.AfterAssessmentModule_MasterRepository.RegisterObjection_MasterRepository;

import com.GAssociatesWeb.GAssociates.Entity.MasterWebEntity.AfterAsessment_Module.RegisterObjection_Entity.RegisterObjection_Entity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface RegisterObjection_MasterRepository extends JpaRepository<RegisterObjection_Entity, Long> {
}
