package com.GAssociatesWeb.GAssociates.Repository.MasterWebRepository.AssessmentModule_MasterRepository.ConsolidatedTaxes_MasterRepository;

import com.GAssociatesWeb.GAssociates.Entity.MasterWebEntity.AssessmentModule_MasterEntity.ConsolidatedTaxes_MasterEntity.ConsolidatedTaxes_MasterEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

public interface ConsolidatedTaxes_MasterRepository extends JpaRepository<ConsolidatedTaxes_MasterEntity, Long> {
    ConsolidatedTaxes_MasterEntity findByTaxNameVc(String taxNameVc);
}