package com.GAssociatesWeb.GAssociates.Repository.MasterWebRepository.PropertyDetails_MasterRepository;

import com.GAssociatesWeb.GAssociates.Entity.MasterWebEntity.PropertyDetails_MasterEntity.OwnerCategory_MasterEntity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface OwnerCategory_MasterRepository extends JpaRepository<OwnerCategory_MasterEntity, Integer> {
}